apiVersion: v1
kind: Namespace
metadata:
  name: devops-training
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: basic-quota
  namespace: devops-training
spec:
  hard:
    pods: "10"
    requests.cpu: "1"
    requests.memory: 1Gib
    limits.cpu: "2"
    limits.memory: 2Gib
