apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  namespace: devops-training
  labels:
    app: my-nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.25
    ports:
    - containerPort: 80
